// GitHub PR bodies cap at ~65536 bytes. We use a safe margin below that limit.
export const DEFAULT_PR_BODY_MAX_BYTES = 60000;

const HEADER = "# PHAX Run Review Handoff\n\nGenerated by PHAX.\n\n";

export interface BuildPrBodyInput {
  readonly reviewHandoffMd: string;
  readonly branch: string;
  readonly maxBytes?: number;
}

export interface BuildPrBodyResult {
  readonly body: string;
  readonly truncated: boolean;
}

export function buildPrBody(input: BuildPrBodyInput): BuildPrBodyResult {
  const { reviewHandoffMd, branch, maxBytes = DEFAULT_PR_BODY_MAX_BYTES } = input;

  const full = HEADER + reviewHandoffMd;
  const fullBytes = Buffer.byteLength(full, "utf8");

  if (fullBytes <= maxBytes) {
    return { body: full, truncated: false };
  }

  const truncationNote =
    `\n\n---\n\n*This body was truncated because it exceeded the GitHub PR body size limit. ` +
    `The full review handoff is available in \`review-handoff.md\` on the \`${branch}\` branch.*`;

  const noteBytes = Buffer.byteLength(truncationNote, "utf8");
  const headerBytes = Buffer.byteLength(HEADER, "utf8");
  const availableForContent = maxBytes - headerBytes - noteBytes;

  if (availableForContent <= 0) {
    return {
      body: HEADER + truncationNote,
      truncated: true,
    };
  }

  const contentBuf = Buffer.from(reviewHandoffMd, "utf8");
  const trimmed = contentBuf.subarray(0, availableForContent).toString("utf8");

  const lastNewline = trimmed.lastIndexOf("\n");
  const safeContent = lastNewline > 0 ? trimmed.substring(0, lastNewline) : trimmed;

  return {
    body: HEADER + safeContent + truncationNote,
    truncated: true,
  };
}
