import { describe, expect, it } from "vitest";
import { buildPrBody, DEFAULT_PR_BODY_MAX_BYTES } from "../../../src/domain/publish/body.js";

const HEADER = "# PHAX Run Review Handoff\n\nGenerated by PHAX.\n\n";

describe("buildPrBody", () => {
  it("wraps content with the deterministic header", () => {
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: "## Summary\n\nShort content.",
      branch: "phax/my-run",
    });
    expect(body.startsWith(HEADER)).toBe(true);
    expect(body).toContain("## Summary\n\nShort content.");
    expect(truncated).toBe(false);
  });

  it("passes through content under the limit unchanged", () => {
    const content = "Hello world";
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: content,
      branch: "main",
      maxBytes: 10000,
    });
    expect(body).toBe(HEADER + content);
    expect(truncated).toBe(false);
  });

  it("truncates and sets truncated:true when content exceeds maxBytes", () => {
    const maxBytes = 400;
    const longContent = "x".repeat(2000);
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: longContent,
      branch: "phax/my-run",
      maxBytes,
    });
    expect(truncated).toBe(true);
    expect(Buffer.byteLength(body, "utf8")).toBeLessThanOrEqual(maxBytes);
  });

  it("truncation note references review-handoff.md and the branch", () => {
    const longContent = "A".repeat(10000);
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: longContent,
      branch: "phax/my-branch",
      maxBytes: 500,
    });
    expect(truncated).toBe(true);
    expect(body).toContain("review-handoff.md");
    expect(body).toContain("phax/my-branch");
  });

  it("uses DEFAULT_PR_BODY_MAX_BYTES when maxBytes is not specified", () => {
    const smallContent = "Short";
    const { truncated } = buildPrBody({
      reviewHandoffMd: smallContent,
      branch: "main",
    });
    expect(truncated).toBe(false);
  });

  it("DEFAULT_PR_BODY_MAX_BYTES is below GitHub 65536 byte limit", () => {
    expect(DEFAULT_PR_BODY_MAX_BYTES).toBeLessThan(65536);
    expect(DEFAULT_PR_BODY_MAX_BYTES).toBeGreaterThan(0);
  });

  it("content just at the limit is not truncated", () => {
    const maxBytes = 200;
    const headerBytes = Buffer.byteLength(HEADER, "utf8");
    const targetContentBytes = maxBytes - headerBytes;
    const content = "a".repeat(targetContentBytes);
    const { truncated } = buildPrBody({
      reviewHandoffMd: content,
      branch: "main",
      maxBytes,
    });
    expect(truncated).toBe(false);
  });

  it("appends compliance section under its own heading when complianceReviewMd is provided", () => {
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: "## Handoff\n\nSome content.",
      branch: "phax/my-run",
      complianceReviewMd: "## Verdict\n\nconformant",
    });
    expect(truncated).toBe(false);
    expect(body).toContain("## Handoff\n\nSome content.");
    expect(body).toContain("## Plan compliance review");
    expect(body).toContain("## Verdict\n\nconformant");
    const handoffIndex = body.indexOf("## Handoff");
    const complianceIndex = body.indexOf("## Plan compliance review");
    expect(complianceIndex).toBeGreaterThan(handoffIndex);
  });

  it("body without complianceReviewMd reproduces today's body", () => {
    const handoff = "## Summary\n\nReview content.";
    const withCompliance = buildPrBody({
      reviewHandoffMd: handoff,
      branch: "main",
      complianceReviewMd: undefined,
    });
    const withoutCompliance = buildPrBody({ reviewHandoffMd: handoff, branch: "main" });
    expect(withCompliance.body).toBe(withoutCompliance.body);
    expect(withCompliance.truncated).toBe(withoutCompliance.truncated);
  });

  it("truncation respects maxBytes when compliance section pushes body over the limit", () => {
    const maxBytes = 400;
    const handoff = "h".repeat(200);
    const compliance = "c".repeat(2000);
    const { body, truncated } = buildPrBody({
      reviewHandoffMd: handoff,
      branch: "phax/my-run",
      complianceReviewMd: compliance,
      maxBytes,
    });
    expect(truncated).toBe(true);
    expect(Buffer.byteLength(body, "utf8")).toBeLessThanOrEqual(maxBytes);
  });
});
