import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  WRITE_COMMAND,
  refreshLock,
  renderGeneratedIndex,
  renderLock,
  renderReleaseModule,
  sha256,
} from "../../../packages/schemas/build/generated.js";
import type { Schema } from "effect";
import {
  FORMAT_DEFINITIONS,
  JSON_SCHEMA_FORMATS,
  renderJsonSchemas,
} from "../../../packages/schemas/build/jsonSchemas.js";
import {
  currentShapeNames,
  firstSupportedRelease,
} from "../../../packages/schemas/build/snapshots.js";
import {
  CURRENT_SHAPES,
  FIRST_SUPPORTED_RELEASE,
  PACKAGE_VERSION,
} from "../../../packages/schemas/src/generated/index.js";
import { readPackageVersion } from "../../../src/cli/commands/usage.js";
import { CURRENT_STAMPS, PHAX_RELEASE } from "../../../src/schemas/release.js";
import { FORMAT_IDS, PRE_SCHEMA_FORMAT_IDS } from "../../../src/schemas/schemaUrl.js";
import { checkSchemas, readSchemasState, writeSchemas } from "../../../scripts/schemas-check.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const state = readSchemasState(repoRoot);

// Derived from the package version, so a release bump never breaks these tests.
const NEWER_RELEASE = `${Number(PACKAGE_VERSION.split(".")[0]) + 1}.0.0`;

/** A current shape map naming every format `next`, for the renderer tests. */
const ALL_NEXT = Object.fromEntries(FORMAT_IDS.map((id) => [id, "next"]));

/** The committed state with one frozen module, pinned by its own bytes. */
function withPinnedModule(path: string): typeof state {
  const bytes = new TextEncoder().encode("// frozen\n");
  return {
    ...state,
    lock: { ...state.lock, [path]: sha256(bytes) },
    historyFiles: new Map([...state.historyFiles, [path, bytes]]),
  };
}

describe("schemas-check on the committed tree", () => {
  it("passes: the generated index, the lock and the snapshots are current", () => {
    expect(state.snapshots.size).toBeGreaterThan(0);
    expect(checkSchemas(state)).toEqual([]);
  });

  // A format born with $schema has no pre-schema shape, so no pre-schema module;
  // a released shape that is no longer current has a module of its own.
  it("pins exactly one frozen module per pre-schema shape and per released shape, by its repo-relative path", () => {
    const expected = [
      ...PRE_SCHEMA_FORMAT_IDS.map((id) => `src/schemas/history/${id}/pre-schema.ts`),
      ...FORMAT_IDS.flatMap((id) =>
        FORMAT_DEFINITIONS[id].releases.map(
          ([release]) => `src/schemas/history/${id}/${release}.ts`,
        ),
      ),
    ].toSorted();
    expect(Object.keys(state.lock)).toEqual(expected);
    expect([...state.historyFiles.keys()]).toEqual(expected);
    expect(readFileSync(join(repoRoot, "packages/schemas/history.lock.json"), "utf8")).toBe(
      renderLock(state.lock),
    );
  });

  it("renders each format's released shape module to its released snapshot", () => {
    const rendered = FORMAT_IDS.flatMap((id) => {
      const entry = JSON_SCHEMA_FORMATS.find((format) => format.format === id);
      if (entry === undefined) throw new Error(`no JSON Schema entry for ${id}`);
      return FORMAT_DEFINITIONS[id].releases.map(([release, shape]) => {
        const { schema } = shape as { readonly schema: Schema.Schema.Any };
        const { files, failures } = renderJsonSchemas([{ ...entry, schema }]);
        expect(failures).toEqual([]);
        return { id, release, content: files.get(entry.fileName) };
      });
    });
    expect(rendered.map(({ id, release }) => `${id}/${release}`)).toEqual(
      expect.arrayContaining(["gate-attribution/0.17.0", "phase-status/0.17.0"]),
    );
    for (const { id, release, content } of rendered) {
      const snapshot = state.snapshots.get(id)?.get(`${release}.schema.json`);
      expect(snapshot, `${id}/${release}`).toBeDefined();
      expect(JSON.parse(content ?? "null"), `${id}/${release}`).toEqual(
        JSON.parse(snapshot ?? "null"),
      );
    }
  });

  it("carries the root package.json version into the generated index", () => {
    const root = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(PACKAGE_VERSION).toBe(root.version);
    expect(state.generatedIndex).toContain(`// Generated by \`${WRITE_COMMAND}\``);
  });

  it("carries the root package.json version into src/schemas/release.ts, which phax --version prints", () => {
    const root = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(PHAX_RELEASE).toBe(root.version);
    expect(readPackageVersion()).toBe(root.version);
    expect(state.releaseModule).toBe(
      renderReleaseModule({ packageVersion: root.version, currentShapes: state.currentShapes }),
    );
    expect(state.releaseModule).toContain(`// Generated by \`${WRITE_COMMAND}\``);
  });

  it("stamps each format with its current shape, or the package version while that is next", () => {
    expect(Object.keys(CURRENT_STAMPS)).toEqual([...FORMAT_IDS]);
    for (const id of FORMAT_IDS) {
      const shape: string = CURRENT_SHAPES[id];
      expect(CURRENT_STAMPS[id], id).toBe(shape === "next" ? PACKAGE_VERSION : shape);
    }
  });

  it("carries the first supported release the snapshots name into the generated index", () => {
    expect(state.firstSupportedRelease).toBe(firstSupportedRelease(state.snapshots));
    expect(FIRST_SUPPORTED_RELEASE).toBe(firstSupportedRelease(state.snapshots));
  });

  it("carries every format's current shape the snapshots name into the generated index", () => {
    const { names, findings } = currentShapeNames(state.snapshots);
    expect(findings).toEqual([]);
    expect(state.currentShapes).toEqual(names);
    expect(CURRENT_SHAPES).toEqual(names);
    expect(Object.keys(CURRENT_SHAPES)).toEqual([...FORMAT_IDS]);
  });

  it("--write would change nothing", () => {
    const written = writeSchemas(state);
    expect(written.mismatched).toEqual([]);
    expect(written.generatedIndex).toBe(state.generatedIndex);
    expect(written.releaseModule).toBe(state.releaseModule);
    expect(written.lock).toBe(
      readFileSync(join(repoRoot, "packages/schemas/history.lock.json"), "utf8"),
    );
    expect(written.snapshotWrites).toEqual(new Map());
    expect(written.snapshotRemovals).toEqual([]);
    expect(checkSchemas(state)).toEqual([]);
  });
});

/**
 * What the check reports for a release module that stamps the package version
 * as `stamped` while package.json says `packageVersion`: one drifted stamp per
 * format whose current shape is `next` (its stamp is the package version), or,
 * when no format is at `next`, one line naming the version.
 */
function staleReleaseModuleFindings(stamped: string, packageVersion: string): string[] {
  const atNext = FORMAT_IDS.filter((id) => state.currentShapes[id] === "next");
  if (atNext.length === 0) {
    return [
      `✗ src/schemas/release.ts does not match package.json version ${packageVersion} — run ${WRITE_COMMAND}`,
    ];
  }
  return atNext.map(
    (id) =>
      `✗ src/schemas/release.ts stamps ${id} with ${stamped}, but its current stamp is ` +
      `${packageVersion} — run ${WRITE_COMMAND}`,
  );
}

describe("schemas-check findings", () => {
  it("fails a stale generated index and release module after a version bump, naming the --write command", () => {
    const bumped = `${PACKAGE_VERSION}9`;
    const [index, ...release] = checkSchemas({ ...state, packageVersion: bumped });
    expect(index).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(index).toContain(WRITE_COMMAND);
    expect(release).toEqual(staleReleaseModuleFindings(PACKAGE_VERSION, bumped));
  });

  it("fails a stale src/schemas/release.ts, naming the --write command", () => {
    const stale = renderReleaseModule({
      packageVersion: "0.1.0",
      currentShapes: state.currentShapes,
    });
    expect(checkSchemas({ ...state, releaseModule: stale })).toEqual(
      staleReleaseModuleFindings("0.1.0", state.packageVersion),
    );
  });

  it("fails a drifted stamp in src/schemas/release.ts, naming the format and both stamps", () => {
    const committed = state.releaseModule ?? "";
    const line = `  "run-status": ${JSON.stringify(CURRENT_STAMPS["run-status"])},\n`;
    expect(committed).toContain(line);
    const drifted = committed.replace(line, '  "run-status": "0.1.0",\n');
    expect(checkSchemas({ ...state, releaseModule: drifted })).toEqual([
      `✗ src/schemas/release.ts stamps run-status with 0.1.0, but its current stamp is ` +
        `${CURRENT_STAMPS["run-status"]} — run ${WRITE_COMMAND}`,
    ]);
  });

  it("fails a missing stamp in src/schemas/release.ts, naming the format", () => {
    const committed = state.releaseModule ?? "";
    const line = `  registry: ${JSON.stringify(CURRENT_STAMPS.registry)},\n`;
    expect(committed).toContain(line);
    expect(checkSchemas({ ...state, releaseModule: committed.replace(line, "") })).toEqual([
      `✗ src/schemas/release.ts stamps registry with no stamp, but its current stamp is ` +
        `${CURRENT_STAMPS.registry} — run ${WRITE_COMMAND}`,
    ]);
  });

  it("fails a stamp that no longer follows a format's snapshots, naming that format", () => {
    // The made-up snapshots say registry gained a next shape: its stamp becomes
    // the package version, and the committed module still names its release.
    const currentShapes = { ...state.currentShapes, registry: "next" };
    const findings = checkSchemas({ ...state, currentShapes });
    expect(findings).toContain(
      `✗ src/schemas/release.ts stamps registry with ${CURRENT_STAMPS.registry}, but its ` +
        `current stamp is ${state.packageVersion} — run ${WRITE_COMMAND}`,
    );
  });

  it("fails a hand-edited src/schemas/release.ts", () => {
    const findings = checkSchemas({
      ...state,
      releaseModule: `${state.releaseModule ?? ""}// edited\n`,
    });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatch(/^✗ src\/schemas\/release\.ts /);
  });

  it("fails a missing src/schemas/release.ts", () => {
    expect(checkSchemas({ ...state, releaseModule: undefined })).toEqual([
      `✗ src/schemas/release.ts does not match package.json version ${state.packageVersion} — run ${WRITE_COMMAND}`,
    ]);
  });

  it("fails a stale FIRST_SUPPORTED_RELEASE, naming the --write command", () => {
    const findings = checkSchemas({ ...state, firstSupportedRelease: NEWER_RELEASE });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(findings[0]).toContain(`first supported release ${NEWER_RELEASE}`);
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a stale CURRENT_SHAPES and CURRENT_STAMPS, naming the expected current shapes and the --write command", () => {
    const currentShapes = { ...state.currentShapes, registry: NEWER_RELEASE };
    const findings = checkSchemas({ ...state, currentShapes });
    expect(findings).toHaveLength(2);
    expect(findings[0]).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(findings[0]).toContain(`current shapes ${NEWER_RELEASE} (registry), `);
    expect(findings[0]).toContain(WRITE_COMMAND);
    expect(findings[1]).toBe(
      `✗ src/schemas/release.ts stamps registry with ${CURRENT_STAMPS.registry}, but its ` +
        `current stamp is ${NEWER_RELEASE} — run ${WRITE_COMMAND}`,
    );
  });

  it("names a single current shape shared by every format once", () => {
    const currentShapes = Object.fromEntries(FORMAT_IDS.map((id) => [id, NEWER_RELEASE]));
    const [finding] = checkSchemas({ ...state, currentShapes });
    expect(finding).toContain(`current shapes ${NEWER_RELEASE} for every format`);
  });

  it("fails a format with no next or release-named snapshot", () => {
    const snapshots = new Map(state.snapshots);
    snapshots.set("registry", new Map([["pre-schema.schema.json", "{}"]]));
    const findings = checkSchemas({ ...state, snapshots });
    expect(findings).toContain(
      `✗ registry: no next or release-named snapshot — run ${WRITE_COMMAND}`,
    );
  });

  it("fails a hand-edited generated index", () => {
    const findings = checkSchemas({
      ...state,
      generatedIndex: `${state.generatedIndex ?? ""}// edited\n`,
    });
    expect(findings).toHaveLength(1);
  });

  it("fails a missing generated index", () => {
    expect(checkSchemas({ ...state, generatedIndex: undefined })).toHaveLength(1);
  });

  it("fails a frozen module that no longer matches its lock entry, naming the --write command", () => {
    const path = "src/schemas/history/phase-record-manifest/0.17.0.ts";
    const pinned = withPinnedModule(path);
    expect(checkSchemas(pinned)).toEqual([]);
    const historyFiles = new Map(pinned.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const findings = checkSchemas({ ...pinned, historyFiles });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toContain(
      `✗ ${path} differs from its packages/schemas/history.lock.json entry`,
    );
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a committed frozen module edited after it was pinned", () => {
    const path = "src/schemas/history/registry/pre-schema.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const findings = checkSchemas({ ...state, historyFiles });
    expect(findings).toEqual([
      expect.stringContaining(`✗ ${path} differs from its packages/schemas/history.lock.json`),
    ]);
  });

  it("fails a frozen module without a lock entry", () => {
    const path = "src/schemas/history/phase-record-manifest/0.18.0.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new Uint8Array());
    const [finding, ...rest] = checkSchemas({ ...state, historyFiles });
    expect(rest).toEqual([]);
    expect(finding).toContain(`✗ ${path} has no packages/schemas/history.lock.json entry`);
    expect(finding).toContain(WRITE_COMMAND);
  });

  it("fails a lock entry naming a module that does not exist", () => {
    const path = "src/schemas/history/phase-record-manifest/0.1.0.ts";
    const lock = { ...state.lock, [path]: sha256("") };
    const [finding, ...rest] = checkSchemas({ ...state, lock });
    expect(rest).toEqual([]);
    expect(finding).toBe(
      `✗ packages/schemas/history.lock.json names ${path}, which does not exist — restore the module`,
    );
  });

  it("fails a lock entry naming a deleted module of a retired format, naming the --write command", () => {
    const path = "src/schemas/history/old-format/pre-schema.ts";
    const lock = { ...state.lock, [path]: sha256("") };
    expect(checkSchemas({ ...state, lock })).toEqual([
      `✗ packages/schemas/history.lock.json names ${path}, a module of a retired format — run ${WRITE_COMMAND}`,
    ]);
  });

  it("--write drops the lock entries of a retired format's deleted modules, and only those", () => {
    const retired = "src/schemas/history/old-format/pre-schema.ts";
    const deleted = "src/schemas/history/phase-record-manifest/0.1.0.ts";
    const lock = { ...state.lock, [retired]: sha256(""), [deleted]: sha256("") };
    const written = writeSchemas({ ...state, lock });
    expect(written.mismatched).toEqual([]);
    const pinned = Object.keys(JSON.parse(written.lock) as Record<string, string>);
    expect(pinned).not.toContain(retired);
    expect(pinned).toContain(deleted);
  });

  it("--write names the current shapes its own snapshot writes record", () => {
    // The registry's shape changed after release 0.1.0: --write records next,
    // and the index it writes already names next.
    const snapshots = new Map(state.snapshots);
    snapshots.set(
      "registry",
      new Map([
        ["pre-schema.schema.json", "{}"],
        ["0.1.0.schema.json", "{}"],
      ]),
    );
    const written = writeSchemas({ ...state, snapshots });
    expect([...written.snapshotWrites.keys()]).toEqual([
      "packages/schemas/snapshots/registry/next.schema.json",
    ]);
    expect(written.generatedIndex).toContain('  registry: "next",\n');
    expect(written.releaseModule).toContain(
      `  registry: ${JSON.stringify(state.packageVersion)},\n`,
    );
  });

  it("--write refuses to change a mismatched entry", () => {
    const path = "src/schemas/history/phase-record-manifest/0.17.0.ts";
    const pinned = withPinnedModule(path);
    const historyFiles = new Map(pinned.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const written = writeSchemas({ ...pinned, historyFiles });
    expect(written.mismatched).toEqual([path]);
  });
});

describe("renderReleaseModule", () => {
  it("renders PHAX_RELEASE as the package version", () => {
    expect(renderReleaseModule({ packageVersion: "1.2.3", currentShapes: ALL_NEXT })).toContain(
      'export const PHAX_RELEASE = "1.2.3";',
    );
  });

  it("stamps a release-named current shape as itself and a next one as the package version", () => {
    const rendered = renderReleaseModule({
      packageVersion: "1.3.0",
      currentShapes: { registry: "1.1.0", "run-status": "next", "gate-attribution": "1.2.0" },
    });
    expect(rendered).toContain(
      "export const CURRENT_STAMPS = {\n" +
        '  registry: "1.1.0",\n' +
        '  "run-status": "1.3.0",\n' +
        '  "gate-attribution": "1.2.0",\n' +
        "} as const;\n",
    );
  });
});

describe("refreshLock and renderGeneratedIndex", () => {
  it("adds missing entries, keeps existing ones and sorts by path", () => {
    const pinned = { "src/history/b.ts": "pinned" };
    const { lock, mismatched } = refreshLock(
      pinned,
      new Map([
        ["src/history/b.ts", "changed"],
        ["src/history/a.ts", "new"],
      ]),
    );
    expect(lock).toEqual({ "src/history/a.ts": sha256("new"), "src/history/b.ts": "pinned" });
    expect(Object.keys(lock)).toEqual(["src/history/a.ts", "src/history/b.ts"]);
    expect(mismatched).toEqual(["src/history/b.ts"]);
  });

  it("renders PACKAGE_VERSION as a const", () => {
    expect(
      renderGeneratedIndex({
        packageVersion: "1.2.3",
        firstSupportedRelease: null,
        currentShapes: ALL_NEXT,
      }),
    ).toContain('export const PACKAGE_VERSION = "1.2.3" as const;');
  });

  it("renders FIRST_SUPPORTED_RELEASE as a string or null", () => {
    expect(
      renderGeneratedIndex({
        packageVersion: "1.2.3",
        firstSupportedRelease: null,
        currentShapes: ALL_NEXT,
      }),
    ).toContain("export const FIRST_SUPPORTED_RELEASE: string | null = null;");
    expect(
      renderGeneratedIndex({
        packageVersion: "1.2.3",
        firstSupportedRelease: "0.17.0",
        currentShapes: ALL_NEXT,
      }),
    ).toContain('export const FIRST_SUPPORTED_RELEASE: string | null = "0.17.0";');
  });

  it("renders CURRENT_SHAPES as a const in FORMAT_IDS order, quoting only the ids that need it", () => {
    const rendered = renderGeneratedIndex({
      packageVersion: "1.2.3",
      firstSupportedRelease: "0.17.0",
      currentShapes: { "gate-attribution": "next", registry: "0.17.0" },
    });
    expect(rendered).toContain(
      'export const CURRENT_SHAPES = {\n  registry: "0.17.0",\n  "gate-attribution": "next",\n} as const;\n',
    );
  });
});

/** A snapshot directory holding one file per snapshot name. */
function dir(...names: string[]): ReadonlyMap<string, string> {
  return new Map(names.map((name) => [`${name}.schema.json`, "{}"] as const));
}

describe("firstSupportedRelease", () => {
  it("is null when no snapshot is release-named: pre-schema and next are not releases", () => {
    expect(firstSupportedRelease(new Map())).toBeNull();
    expect(firstSupportedRelease(new Map([["registry", dir("pre-schema", "next")]]))).toBeNull();
  });

  it("is the lowest release-named snapshot across every format directory", () => {
    const snapshots = new Map([
      ["registry", dir("pre-schema", "0.18.0", "next")],
      ["run-status", dir("pre-schema", "0.17.0", "0.20.0")],
      ["gate-attribution", dir("0.9.1")],
    ]);
    expect(firstSupportedRelease(snapshots)).toBe("0.9.1");
  });

  it("ignores a directory that names no format and a hidden one", () => {
    const snapshots = new Map([
      ["registry", dir("0.18.0")],
      ["launch-codes", dir("0.1.0")],
      [".cache", dir("0.2.0")],
    ]);
    expect(firstSupportedRelease(snapshots)).toBe("0.18.0");
  });
});
