import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  WRITE_COMMAND,
  refreshLock,
  renderGeneratedIndex,
  renderLock,
  renderReleaseModule,
  sha256,
} from "../../../packages/schemas/build/generated.js";
import { firstSupportedRelease } from "../../../packages/schemas/build/snapshots.js";
import {
  FIRST_SUPPORTED_RELEASE,
  PACKAGE_VERSION,
} from "../../../packages/schemas/src/generated/index.js";
import { readPackageVersion } from "../../../src/cli/commands/usage.js";
import { PHAX_RELEASE } from "../../../src/schemas/release.js";
import { FORMAT_IDS } from "../../../src/schemas/schemaUrl.js";
import { checkSchemas, readSchemasState, writeSchemas } from "../../../scripts/schemas-check.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const state = readSchemasState(repoRoot);

/** The committed state with one frozen module, pinned by its own bytes. */
function withPinnedModule(path: string): typeof state {
  const bytes = new TextEncoder().encode("// frozen\n");
  return {
    ...state,
    lock: { ...state.lock, [path]: sha256(bytes) },
    historyFiles: new Map([...state.historyFiles, [path, bytes]]),
  };
}

describe("schemas-check on the committed tree", () => {
  it("passes: the generated index, the lock and the snapshots are current", () => {
    expect(state.snapshots.size).toBeGreaterThan(0);
    expect(checkSchemas(state)).toEqual([]);
  });

  it("pins exactly one frozen module per format id, by its repo-relative path", () => {
    const expected = FORMAT_IDS.map((id) => `src/schemas/history/${id}/pre-schema.ts`).toSorted();
    expect(Object.keys(state.lock)).toEqual(expected);
    expect([...state.historyFiles.keys()]).toEqual(expected);
    expect(readFileSync(join(repoRoot, "packages/schemas/history.lock.json"), "utf8")).toBe(
      renderLock(state.lock),
    );
  });

  it("carries the root package.json version into the generated index", () => {
    const root = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(PACKAGE_VERSION).toBe(root.version);
    expect(state.generatedIndex).toContain(`// Generated by \`${WRITE_COMMAND}\``);
  });

  it("carries the root package.json version into src/schemas/release.ts, which phax --version prints", () => {
    const root = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(PHAX_RELEASE).toBe(root.version);
    expect(readPackageVersion()).toBe(root.version);
    expect(state.releaseModule).toBe(renderReleaseModule({ packageVersion: root.version }));
    expect(state.releaseModule).toContain(`// Generated by \`${WRITE_COMMAND}\``);
  });

  it("carries the first supported release into the generated index: none is released yet", () => {
    expect(state.firstSupportedRelease).toBeNull();
    expect(FIRST_SUPPORTED_RELEASE).toBeNull();
  });

  it("--write would change nothing", () => {
    const written = writeSchemas(state);
    expect(written.mismatched).toEqual([]);
    expect(written.generatedIndex).toBe(state.generatedIndex);
    expect(written.releaseModule).toBe(state.releaseModule);
    expect(written.lock).toBe(
      readFileSync(join(repoRoot, "packages/schemas/history.lock.json"), "utf8"),
    );
    expect(written.snapshotWrites).toEqual(new Map());
    expect(written.snapshotRemovals).toEqual([]);
    expect(checkSchemas(state)).toEqual([]);
  });
});

describe("schemas-check findings", () => {
  it("fails a stale generated index and release module after a version bump, naming the --write command", () => {
    const bumped = `${PACKAGE_VERSION}9`;
    const findings = checkSchemas({ ...state, packageVersion: bumped });
    expect(findings).toHaveLength(2);
    expect(findings[0]).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(findings[0]).toContain(WRITE_COMMAND);
    expect(findings[1]).toBe(
      `✗ src/schemas/release.ts does not match package.json version ${bumped} — run ${WRITE_COMMAND}`,
    );
  });

  it("fails a stale src/schemas/release.ts, naming the --write command", () => {
    const stale = renderReleaseModule({ packageVersion: "0.1.0" });
    expect(checkSchemas({ ...state, releaseModule: stale })).toEqual([
      `✗ src/schemas/release.ts does not match package.json version ${state.packageVersion} — run ${WRITE_COMMAND}`,
    ]);
  });

  it("fails a hand-edited src/schemas/release.ts", () => {
    const findings = checkSchemas({
      ...state,
      releaseModule: `${state.releaseModule ?? ""}// edited\n`,
    });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatch(/^✗ src\/schemas\/release\.ts /);
  });

  it("fails a missing src/schemas/release.ts", () => {
    expect(checkSchemas({ ...state, releaseModule: undefined })).toEqual([
      `✗ src/schemas/release.ts does not match package.json version ${state.packageVersion} — run ${WRITE_COMMAND}`,
    ]);
  });

  it("fails a stale FIRST_SUPPORTED_RELEASE, naming the --write command", () => {
    const findings = checkSchemas({ ...state, firstSupportedRelease: "0.17.0" });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(findings[0]).toContain("first supported release 0.17.0");
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a hand-edited generated index", () => {
    const findings = checkSchemas({
      ...state,
      generatedIndex: `${state.generatedIndex ?? ""}// edited\n`,
    });
    expect(findings).toHaveLength(1);
  });

  it("fails a missing generated index", () => {
    expect(checkSchemas({ ...state, generatedIndex: undefined })).toHaveLength(1);
  });

  it("fails a frozen module that no longer matches its lock entry, naming the --write command", () => {
    const path = "src/schemas/history/phase-record-manifest/0.17.0.ts";
    const pinned = withPinnedModule(path);
    expect(checkSchemas(pinned)).toEqual([]);
    const historyFiles = new Map(pinned.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const findings = checkSchemas({ ...pinned, historyFiles });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toContain(
      `✗ ${path} differs from its packages/schemas/history.lock.json entry`,
    );
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a committed frozen module edited after it was pinned", () => {
    const path = "src/schemas/history/registry/pre-schema.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const findings = checkSchemas({ ...state, historyFiles });
    expect(findings).toEqual([
      expect.stringContaining(`✗ ${path} differs from its packages/schemas/history.lock.json`),
    ]);
  });

  it("fails a frozen module without a lock entry", () => {
    const path = "src/schemas/history/phase-record-manifest/0.18.0.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new Uint8Array());
    const [finding, ...rest] = checkSchemas({ ...state, historyFiles });
    expect(rest).toEqual([]);
    expect(finding).toContain(`✗ ${path} has no packages/schemas/history.lock.json entry`);
    expect(finding).toContain(WRITE_COMMAND);
  });

  it("fails a lock entry naming a module that does not exist", () => {
    const path = "src/schemas/history/phase-record-manifest/0.1.0.ts";
    const lock = { ...state.lock, [path]: sha256("") };
    const [finding, ...rest] = checkSchemas({ ...state, lock });
    expect(rest).toEqual([]);
    expect(finding).toBe(
      `✗ packages/schemas/history.lock.json names ${path}, which does not exist — restore the module`,
    );
  });

  it("--write refuses to change a mismatched entry", () => {
    const path = "src/schemas/history/phase-record-manifest/0.17.0.ts";
    const pinned = withPinnedModule(path);
    const historyFiles = new Map(pinned.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const written = writeSchemas({ ...pinned, historyFiles });
    expect(written.mismatched).toEqual([path]);
  });
});

describe("refreshLock and renderGeneratedIndex", () => {
  it("adds missing entries, keeps existing ones and sorts by path", () => {
    const pinned = { "src/history/b.ts": "pinned" };
    const { lock, mismatched } = refreshLock(
      pinned,
      new Map([
        ["src/history/b.ts", "changed"],
        ["src/history/a.ts", "new"],
      ]),
    );
    expect(lock).toEqual({ "src/history/a.ts": sha256("new"), "src/history/b.ts": "pinned" });
    expect(Object.keys(lock)).toEqual(["src/history/a.ts", "src/history/b.ts"]);
    expect(mismatched).toEqual(["src/history/b.ts"]);
  });

  it("renders PACKAGE_VERSION as a const", () => {
    expect(
      renderGeneratedIndex({ packageVersion: "1.2.3", firstSupportedRelease: null }),
    ).toContain('export const PACKAGE_VERSION = "1.2.3" as const;');
  });

  it("renders FIRST_SUPPORTED_RELEASE as a string or null", () => {
    expect(
      renderGeneratedIndex({ packageVersion: "1.2.3", firstSupportedRelease: null }),
    ).toContain("export const FIRST_SUPPORTED_RELEASE: string | null = null;");
    expect(
      renderGeneratedIndex({ packageVersion: "1.2.3", firstSupportedRelease: "0.17.0" }),
    ).toContain('export const FIRST_SUPPORTED_RELEASE: string | null = "0.17.0";');
  });
});

/** A snapshot directory holding one file per snapshot name. */
function dir(...names: string[]): ReadonlyMap<string, string> {
  return new Map(names.map((name) => [`${name}.schema.json`, "{}"] as const));
}

describe("firstSupportedRelease", () => {
  it("is null when no snapshot is release-named: pre-schema and next are not releases", () => {
    expect(firstSupportedRelease(new Map())).toBeNull();
    expect(firstSupportedRelease(new Map([["registry", dir("pre-schema", "next")]]))).toBeNull();
  });

  it("is the lowest release-named snapshot across every format directory", () => {
    const snapshots = new Map([
      ["registry", dir("pre-schema", "0.18.0", "next")],
      ["run-status", dir("pre-schema", "0.17.0", "0.20.0")],
      ["gate-pending", dir("0.9.1")],
    ]);
    expect(firstSupportedRelease(snapshots)).toBe("0.9.1");
  });

  it("ignores a directory that names no format and a hidden one", () => {
    const snapshots = new Map([
      ["registry", dir("0.18.0")],
      ["launch-codes", dir("0.1.0")],
      [".cache", dir("0.2.0")],
    ]);
    expect(firstSupportedRelease(snapshots)).toBe("0.18.0");
  });
});
