import { readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Either, JSONSchema } from "effect";
import { describe, expect, it } from "vitest";
import {
  WRITE_COMMAND,
  refreshLock,
  renderGeneratedIndex,
  sha256,
} from "../../../packages/schemas/build/generated.js";
import { PACKAGE_VERSION } from "../../../packages/schemas/src/generated/index.js";
import {
  PhaseRecordManifestV2Schema,
  decodePhaseRecordManifestV2,
} from "../../../packages/schemas/src/history/phase-record-manifest/v2.js";
import { checkSchemas, readSchemasState, writeSchemas } from "../../../scripts/schemas-check.js";
import {
  RunRecordManifestSchema,
  decodeRunRecordManifest,
} from "../../../src/schemas/runRecord.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const state = readSchemasState(repoRoot);

describe("schemas-check on the committed tree", () => {
  it("passes: the generated index and the lock are current", () => {
    expect(checkSchemas(state)).toEqual([]);
  });

  it("pins every frozen module", () => {
    expect(Object.keys(state.lock)).toEqual([
      "src/history/authoring-record-manifest/v1.ts",
      "src/history/compliance-review/v1.ts",
      "src/history/gate-attribution/v0.ts",
      "src/history/gate-diagnostics/v0.ts",
      "src/history/gate-pending/v0.ts",
      "src/history/phase-file-reconciliation/v0.ts",
      "src/history/phase-record-manifest/v1.ts",
      "src/history/phase-record-manifest/v2.ts",
      "src/history/phase-status/v1.ts",
      "src/history/phax-plan/v1.ts",
      "src/history/plan-approvals/v1.ts",
      "src/history/plan-document/v1.ts",
      "src/history/registry/v1.ts",
      "src/history/run-status/v1.ts",
      "src/history/spec-approvals/v1.ts",
      "src/history/spec-document/v1.ts",
    ]);
  });

  it("carries the root package.json version into the generated index", () => {
    const root = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(PACKAGE_VERSION).toBe(root.version);
    expect(state.generatedIndex).toContain(`// Generated by \`${WRITE_COMMAND}\``);
  });

  it("--write would change nothing", () => {
    const written = writeSchemas(state);
    expect(written.mismatched).toEqual([]);
    expect(written.generatedIndex).toBe(state.generatedIndex);
    expect(written.lock).toBe(
      readFileSync(join(repoRoot, "packages/schemas/history.lock.json"), "utf8"),
    );
  });
});

describe("schemas-check findings", () => {
  it("fails a stale generated index, naming the --write command", () => {
    const findings = checkSchemas({ ...state, packageVersion: `${PACKAGE_VERSION}9` });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatch(/^✗ packages\/schemas\/src\/generated\/index\.ts /);
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a hand-edited generated index", () => {
    const findings = checkSchemas({
      ...state,
      generatedIndex: `${state.generatedIndex ?? ""}// edited\n`,
    });
    expect(findings).toHaveLength(1);
  });

  it("fails a missing generated index", () => {
    expect(checkSchemas({ ...state, generatedIndex: undefined })).toHaveLength(1);
  });

  it("fails a frozen module that no longer matches its lock entry, naming the --write command", () => {
    const path = "src/history/phase-record-manifest/v1.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const findings = checkSchemas({ ...state, historyFiles });
    expect(findings).toHaveLength(1);
    expect(findings[0]).toContain(`✗ packages/schemas/${path} differs from its history.lock.json`);
    expect(findings[0]).toContain(WRITE_COMMAND);
  });

  it("fails a frozen module without a lock entry", () => {
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set("src/history/phase-record-manifest/v3.ts", new Uint8Array());
    const [finding, ...rest] = checkSchemas({ ...state, historyFiles });
    expect(rest).toEqual([]);
    expect(finding).toContain("has no history.lock.json entry");
    expect(finding).toContain(WRITE_COMMAND);
  });

  it("fails a lock entry naming a module that does not exist", () => {
    const lock = { ...state.lock, "src/history/phase-record-manifest/v0.ts": sha256("") };
    const [finding, ...rest] = checkSchemas({ ...state, lock });
    expect(rest).toEqual([]);
    expect(finding).toContain("which does not exist");
  });

  it("--write refuses to change a mismatched entry", () => {
    const path = "src/history/phase-record-manifest/v2.ts";
    const historyFiles = new Map(state.historyFiles);
    historyFiles.set(path, new TextEncoder().encode("// changed\n"));
    const written = writeSchemas({ ...state, historyFiles });
    expect(written.mismatched).toEqual([path]);
  });
});

describe("refreshLock and renderGeneratedIndex", () => {
  it("adds missing entries, keeps existing ones and sorts by path", () => {
    const pinned = { "src/history/b.ts": "pinned" };
    const { lock, mismatched } = refreshLock(
      pinned,
      new Map([
        ["src/history/b.ts", "changed"],
        ["src/history/a.ts", "new"],
      ]),
    );
    expect(lock).toEqual({ "src/history/a.ts": sha256("new"), "src/history/b.ts": "pinned" });
    expect(Object.keys(lock)).toEqual(["src/history/a.ts", "src/history/b.ts"]);
    expect(mismatched).toEqual(["src/history/b.ts"]);
  });

  it("renders PACKAGE_VERSION as a const", () => {
    expect(renderGeneratedIndex({ packageVersion: "1.2.3" })).toContain(
      'export const PACKAGE_VERSION = "1.2.3" as const;',
    );
  });
});

describe("the frozen v2 twin is faithful to phax's current schema", () => {
  it("has the same JSON Schema", () => {
    expect(JSONSchema.make(PhaseRecordManifestV2Schema)).toEqual(
      JSONSchema.make(RunRecordManifestSchema),
    );
  });

  const fixturesDir = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "fixtures",
    "phase-record-manifest",
  );
  const documents = [
    ...readdirSync(join(fixturesDir, "v1")).map((name) => join(fixturesDir, "v1", name)),
    ...readdirSync(join(fixturesDir, "v2")).map((name) => join(fixturesDir, "v2", name)),
  ].map((path) => [path.slice(fixturesDir.length + 1), JSON.parse(readFileSync(path, "utf8"))]);

  it.each(documents)("gives the same verdict and value as phax on %s", (_name, document) => {
    const frozen = decodePhaseRecordManifestV2(document);
    const phax = decodeRunRecordManifest(document);
    expect(Either.isRight(frozen)).toBe(Either.isRight(phax));
    if (Either.isRight(frozen) && Either.isRight(phax)) expect(frozen.right).toEqual(phax.right);
  });
});
