// Generated by `pnpm exec tsx scripts/schemas-check.ts --write` — do not edit.
// The root package.json version: the running version `phax --version`
// prints and that readers compare a document's $schema stamp against.
export const PHAX_RELEASE = "0.21.0";
// Each format's current stamp, which phax writes in its $schema: the
// format's latest release-named snapshot, or PHAX_RELEASE while
// packages/schemas/snapshots/<format id>/next.schema.json exists.
export const CURRENT_STAMPS = {
  registry: "0.17.0",
  "run-status": "0.17.0",
  "phase-status": "0.20.0",
  "phax-plan": "0.17.0",
  "compliance-review": "0.17.0",
  "plan-approvals": "0.17.0",
  "spec-approvals": "0.17.0",
  "phase-record-manifest": "0.17.0",
  "authoring-record-manifest": "0.17.0",
  "gate-attribution": "0.21.0",
  "phase-file-reconciliation": "0.17.0",
  "spec-document": "0.17.0",
  "plan-document": "0.20.0",
  "plan-approval-record": "0.19.0",
  "spec-approval-record": "0.19.0",
  "gate-request": "0.20.0",
  "brief-request": "0.20.0",
  "brief-record": "0.21.0",
  "gate-report": "0.21.0",
  "brief-report": "0.21.0",
} as const;
