// Generated by `pnpm exec tsx scripts/schemas-check.ts --write` — do not edit.
// The root package.json version: the release `phax --version` prints and
// every persisted document names in its $schema.
export const PHAX_RELEASE = "0.17.0";
